services:

  symfony.container: {synthetic: true}

  container:
    class: Acclimate\Container\CompositeContainer
    arguments:
      - ["@slim.container", "@acclimate.symfony.container"]

  acclimate.container:
    class: Acclimate\Container\ContainerAcclimator

  acclimate.symfony.container:
    class: Acclimate\Container\ContainerAcclimator
    factory: [@acclimate.container, acclimate]
    arguments:
      - @symfony.container

  slim.container:
    class: Slim\Container
    arguments:
      - %settings%