parameters:

  settings: []

services:

  slim:
    class: 'Slim\App'
    arguments:
      - @container

  owl.pellet.route.loader:
    class: 'GreatOwl\Application\Startup\RouteLoader'
    arguments:
      - @slim
      - @container
      - %routes%
